name: Build macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          brew update
          brew install sdl2 freetype ffmpeg

      - name: Set up pkg-config path
        run: |
          echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig:$(brew --prefix ffmpeg)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH=$(brew --prefix) \
                -S .

      - name: Build
        run: cmake --build build

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: sdlMS-macos
          path: build/sdlms/sdlMS
          if-no-files-found: error
